import { User, type UserDocument } from '../models/User';
import { ApiError } from '../utils/ApiError';
import { logger } from '../utils/logger';
import { storage } from './storage';
import type { VerifiedUpload } from '../middleware/upload';

/**
 * Profile photographs.
 *
 * Filed under their own storage prefix, alongside — not inside — the `public/`
 * area. That is deliberate: a profile photo is a picture of a person's face,
 * which is personal data, so it follows the same rule as the before/after
 * photographs. The unauthenticated `/api/media` route can only address keys
 * under `public/`, so nothing here is reachable through it however the request
 * is crafted. The bytes are served only by the authenticated avatar route, to
 * the owner or to an admin.
 */
const AVATAR_PREFIX = 'avatars';

const CONTENT_TYPES: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
};

/**
 * Replaces a user's photo.
 *
 * Bytes first, then the row — the same ordering as `storeAsset`. If the write
 * to Mongo fails the new object is removed again, so a failed upload cannot
 * leave an orphan on disk. The previous object is discarded only after the row
 * points at the new one, so a crash in between costs a stale file rather than
 * a user whose avatar 404s.
 */
export async function saveAvatar(user: UserDocument, upload: VerifiedUpload): Promise<Date> {
  const previousKey = user.avatarKey;
  const stored = await storage.save(upload.buffer, {
    extension: upload.extension,
    prefix: AVATAR_PREFIX,
  });

  const updatedAt = new Date();
  try {
    await User.updateOne(
      { _id: user._id },
      { $set: { avatarKey: stored.key, avatarUpdatedAt: updatedAt } },
    );
  } catch (error) {
    await storage.remove(stored.key).catch(() => undefined);
    throw error;
  }

  await discard(previousKey);
  return updatedAt;
}

export async function removeAvatar(user: UserDocument): Promise<void> {
  if (!user.avatarKey) return;
  await User.updateOne({ _id: user._id }, { $unset: { avatarKey: '', avatarUpdatedAt: '' } });
  await discard(user.avatarKey);
}

/** Opens a user's photo for streaming. */
export async function openAvatar(avatarKey: string) {
  // Keys are generated by the storage adapter and never taken from a request,
  // but the prefix is asserted anyway so a corrupted row cannot be used to
  // read outside the avatar area.
  if (!avatarKey.startsWith(`${AVATAR_PREFIX}/`)) {
    throw ApiError.notFound('That image could not be found.');
  }
  if (!(await storage.exists(avatarKey))) {
    throw ApiError.notFound('That image could not be found.');
  }

  const extension = avatarKey.slice(avatarKey.lastIndexOf('.'));
  return {
    stream: storage.createReadStream(avatarKey),
    contentType: CONTENT_TYPES[extension] ?? 'application/octet-stream',
  };
}

/** Losing a replaced file is not a reason to fail the request that replaced it. */
async function discard(key: string | undefined): Promise<void> {
  if (!key) return;
  try {
    await storage.remove(key);
  } catch (error) {
    logger.warn('Could not discard replaced avatar', { key, error: String(error) });
  }
}
