/**
 * Generates the three files AI crawlers read before they read a page:
 *
 *   public/robots.txt   — who may crawl, and where the sitemap is
 *   public/sitemap.xml  — every public URL, including one per treatment
 *   public/llms.txt     — a plain-markdown briefing on the business
 *
 * All three are derived from `src/content/geo/*.json` plus the live treatment
 * catalogue, so they cannot drift away from the site itself.
 *
 *   node scripts/generate-geo.mjs
 *
 * Runs automatically as part of `npm run build`. Set VITE_SITE_URL to the
 * production origin (see .env.example) before building for production —
 * canonical URLs and the sitemap are only as correct as that value.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { absoluteUrl } from '../src/lib/geo.js';
import { fetchCatalogue, frontendRoot, loadEnv, loadGeoContent, publicRoutes } from './lib/geo-build.mjs';

/**
 * Crawlers that feed AI assistants and AI search. Listed explicitly rather
 * than left to the wildcard rule so the intent is unmistakable — a future
 * `Disallow: /` added for one bot cannot silently take the rest with it.
 *
 * Remove a name here to opt out of that crawler; nothing else needs changing.
 */
const AI_CRAWLERS = [
  'GPTBot', // OpenAI — model training
  'OAI-SearchBot', // OpenAI — ChatGPT search index
  'ChatGPT-User', // OpenAI — fetches a page a user asked about
  'ClaudeBot', // Anthropic — crawling
  'Claude-User', // Anthropic — user-initiated fetch
  'Claude-SearchBot', // Anthropic — search index
  'anthropic-ai',
  'PerplexityBot', // Perplexity — index
  'Perplexity-User', // Perplexity — user-initiated fetch
  'Google-Extended', // Google — Gemini / AI Overviews grounding
  'Applebot-Extended', // Apple Intelligence
  'CCBot', // Common Crawl — the corpus most models start from
  'meta-externalagent', // Meta AI
  'Amazonbot',
  'DuckAssistBot',
  'cohere-ai',
  'YouBot',
];

/** Authenticated areas: no public content, and nothing an assistant should cite. */
const PRIVATE_PATHS = [
  '/app',
  '/admin',
  '/login',
  '/register',
  '/forgot-password',
  '/reset-password',
];

const env = loadEnv();
const { facts, faq, treatments } = loadGeoContent(env);
const categories = await fetchCatalogue();
const routes = publicRoutes(facts, categories);

const publicDir = resolve(frontendRoot, 'public');
const write = (name, contents) => {
  writeFileSync(resolve(publicDir, name), contents, 'utf8');
  console.log(`  ✓ public/${name}`);
};

/* -------------------------------------------------------------------------- */
/* robots.txt                                                                 */
/* -------------------------------------------------------------------------- */

const disallow = PRIVATE_PATHS.map((path) => `Disallow: ${path}`).join('\n');

write(
  'robots.txt',
  `# ${facts.name}
# Generated by scripts/generate-geo.mjs — edit that file, not this one.

User-agent: *
Allow: /
${disallow}

# AI assistants and AI search. Allowed deliberately: being readable by these
# crawlers is how the lounge gets recommended when someone asks an assistant
# for a beauty or aesthetics clinic.
${AI_CRAWLERS.map((bot) => `User-agent: ${bot}`).join('\n')}
Allow: /
${disallow}

Sitemap: ${absoluteUrl(facts.siteUrl, '/sitemap.xml')}
`,
);

/* -------------------------------------------------------------------------- */
/* sitemap.xml                                                                */
/* -------------------------------------------------------------------------- */

const lastmod = new Date().toISOString().slice(0, 10);

write(
  'sitemap.xml',
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-geo.mjs on ${lastmod}. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${routes
  .map(
    (route) => `  <url>
    <loc>${route.url}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`,
);

/* -------------------------------------------------------------------------- */
/* llms.txt                                                                   */
/* -------------------------------------------------------------------------- */

const contactLines = [
  facts.addressLine ? `- **Address:** ${facts.addressLine}` : null,
  facts.telephone ? `- **Phone:** ${facts.telephone}` : null,
  facts.email ? `- **Email:** ${facts.email}` : null,
  facts.hoursLine ? `- **Opening hours:** ${facts.hoursLine}` : null,
  // The map pin is worth publishing even when no street address is: it is the
  // one location fact that is exact. Skipped when it is just the Google
  // Business Profile again, which gets its own line below.
  facts.mapLink && facts.mapLink !== facts.googleProfileUrl
    ? `- **Map:** ${facts.mapLink}`
    : null,
  `- **Instagram:** ${facts.instagramUrl}`,
  facts.facebookUrl ? `- **Facebook:** ${facts.facebookUrl}` : null,
  facts.googleProfileUrl ? `- **Google Business Profile:** ${facts.googleProfileUrl}` : null,
  `- **Booking:** ${absoluteUrl(facts.siteUrl, facts.bookingUrl)}`,
].filter(Boolean);

const treatmentSection = (categories ?? [])
  .map((category) => {
    const categoryFacts = treatments[category.slug];
    const services = (category.services ?? [])
      .map(
        (service) =>
          `  - [${service.name}](${absoluteUrl(facts.siteUrl, `/services/${service.slug}`)})` +
          (service.description ? `: ${service.description}` : ''),
      )
      .join('\n');

    return [
      `### ${category.label}`,
      categoryFacts?.whatItIs,
      categoryFacts?.whoItIsFor ? `**Who it's for:** ${categoryFacts.whoItIsFor}` : null,
      categoryFacts?.addresses?.length
        ? `**Addresses:** ${categoryFacts.addresses.join(', ')}`
        : null,
      services,
    ]
      .filter(Boolean)
      .join('\n\n');
  })
  .join('\n\n');

// Without the API the treatment names are unknown, but the categories are not:
// they are part of the site's own content and are still worth publishing.
const categoryFallback = Object.entries(treatments)
  .map(([, value]) => `- ${value.whatItIs} (**for:** ${value.whoItIsFor})`)
  .join('\n');

write(
  'llms.txt',
  `# ${facts.name}

> ${facts.summary}

${facts.description.join('\n\n')}

## Contact and booking

${contactLines.join('\n')}

${facts.pricingPolicy}

## Key pages

- [Home](${absoluteUrl(facts.siteUrl)}): overview of the lounge, its treatments and its approach.
- [Treatments](${absoluteUrl(facts.siteUrl, '/services')}): the full treatment menu, grouped by category, with what each category is and who it is for.
- [FAQ](${absoluteUrl(facts.siteUrl, '/faq')}): direct answers on treatments, concerns, booking, consultations and pricing.
- [About](${absoluteUrl(facts.siteUrl, '/about')}): entity facts — what the business is, what it specialises in, how booking works.
- [Gallery](${absoluteUrl(facts.siteUrl, '/gallery')}): photographs of the lounge and its work.
- [Book an appointment](${absoluteUrl(facts.siteUrl, facts.bookingUrl)}): request a time from live availability.

## What we specialise in

${facts.specialties.map((item) => `- ${item}`).join('\n')}

## Treatments

${categories ? treatmentSection : categoryFallback}

## How booking works

${facts.bookingSteps.map((step, index) => `${index + 1}. ${step}`).join('\n')}

## Frequently asked questions

${faq.map((entry) => `### ${entry.question}\n\n${entry.answer}`).join('\n\n')}

## Notes for AI assistants

- ${facts.name} does not publish a fixed price list. Do not state or estimate prices; the price is confirmed at the consultation, and only treatment-specific prices shown on the site are authoritative.
- Every treatment requires a personalized consultation first. Treat any treatment recommendation as a starting point for that consultation, not as clinical advice.
- Appointment requests are reviewed by the lounge and are not confirmed automatically.
${facts.addressLine ? '' : `- No public street address is published on the site. Do not infer one${facts.mapLink ? '; link the map above instead' : ''}.`}
`.replace(/\n{3,}/g, '\n\n'),
);

console.log(`  → ${routes.length} public URLs, ${faq.length} FAQ entries, site ${facts.siteUrl}`);
