import { randomUUID } from 'node:crypto';
import { createReadStream, existsSync } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';
import { logger } from '../../utils/logger';
import type { StorageAdapter, StoredObject } from './types';

/**
 * Filesystem storage.
 *
 * Keys are `<yyyy>/<mm>/<uuid><ext>`: sharding by month keeps any single
 * directory small, and the UUID means a stored name never derives from
 * anything a user supplied. The original filename is metadata on the document,
 * not part of the path, so a malicious upload name cannot influence where the
 * bytes land.
 */
export class LocalDiskAdapter implements StorageAdapter {
  readonly name = 'local';
  private readonly root: string;

  constructor(rootDir: string) {
    this.root = path.resolve(process.cwd(), rootDir);
  }

  /**
   * Resolves a key inside the storage root, refusing anything that escapes it.
   * Keys are generated by `save`, but this is the boundary that makes a
   * corrupted or hand-edited database row unable to read `../../.env`.
   */
  private resolveKey(key: string): string {
    const target = path.resolve(this.root, key);
    const root = this.root.endsWith(path.sep) ? this.root : this.root + path.sep;
    if (target !== this.root && !target.startsWith(root)) {
      throw new Error(`Storage key escapes the storage root: ${key}`);
    }
    return target;
  }

  async save(buffer: Buffer, options: { extension: string }): Promise<StoredObject> {
    const now = new Date();
    const folder = `${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, '0')}`;
    const key = `${folder}/${randomUUID()}${options.extension}`;
    const target = this.resolveKey(key);

    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, buffer, { flag: 'wx' });

    return { key, sizeBytes: buffer.byteLength };
  }

  createReadStream(key: string): Readable {
    return createReadStream(this.resolveKey(key));
  }

  async exists(key: string): Promise<boolean> {
    try {
      const info = await stat(this.resolveKey(key));
      return info.isFile();
    } catch {
      return false;
    }
  }

  async remove(key: string): Promise<void> {
    try {
      await rm(this.resolveKey(key), { force: true });
    } catch (error) {
      // A missing file is the desired end state, so never fail the request.
      logger.warn('Could not remove stored object', { key, error: String(error) });
    }
  }

  /** Called once on boot so a misconfigured path fails loudly and early. */
  async ensureReady(): Promise<void> {
    await mkdir(this.root, { recursive: true });
    if (!existsSync(this.root)) {
      throw new Error(`Upload directory could not be created: ${this.root}`);
    }
  }
}
